# Generated by Django 4.2.1 on 2023-05-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="slot",
            field=models.CharField(max_length=3, null=True),
        ),
    ]
